DROP TABLE IF EXISTS JOBS;
 

CREATE TABLE JOBS (
  id INT NOT NULL AUTO_INCREMENT,
  job_id INT NULL DEFAULT NULL,
  job_name VARCHAR(255) NULL DEFAULT NULL,
  regular_expression VARCHAR(255) NULL DEFAULT NULL,
  job_enable INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id));

 
 